### ISSUE TITLE
此时间官方刚刚更新了一些东西.

### ISSUE THREAD

**Issue by Fusu12** [maxiaoxiong/noss#13]
看下是否需要update

**Comment by githublister** [comment]
就TP的私钥报错啊
是不是要转格式

**Comment by maxiaoxiong** [comment]
@Fusu12 官方更新太快了，这几天加了很多东西。代码基本刚改好就不能用了。放弃这个项目了。后续我出一个文档介绍一下这个项目方都是怎么搞得
