### ISSUE TITLE
请问私匙需要用hex格式的吗 还是nsec开头的就行？

### ISSUE THREAD

**Issue by Swagger5942** [maxiaoxiong/noss#8]
看terminal里面一堆挖掘成功但是一查balance一个都没有 不知道是不是自己设置错了。。还是说有延迟呀

**Comment by fcqiao** [comment]
挖掘成功指的是挖出符合难度的eventID 不代表挖出了铭文

**Comment by alwaysc** [comment]
nsec开头的就行
